<link rel="icon" href="assets/images/favicon.png">

<!-- style -->
<link rel="stylesheet" href="assets/css/style.css">
<link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
{{--<link rel="stylesheet" href="assets/css/bootstrap.min.css">--}}
<link rel="stylesheet" href="assets/css/normalize.css">
<link rel="stylesheet" href="assets/css/font-awesome.min.css">
<link rel="stylesheet" href="assets/css/transitions.css">
<link rel="stylesheet" href="assets/css/prettyPhoto.css">
<link rel="stylesheet" href="assets/css/swiper.min.css">
<link rel="stylesheet" href="assets/css/jquery-ui.css">
<link rel="stylesheet" href="assets/css/animate.css">
<link rel="stylesheet" href="assets/css/owl.theme.css">
<link rel="stylesheet" href="assets/css/owl.carousel.css">
<link rel="stylesheet" href="assets/css/owl.theme.default.css">
<link rel="stylesheet" href="assets/css/customScrollbar.css">
<link rel="stylesheet" href="assets/css/icomoon.css">
<link rel="stylesheet" href="assets/css/main.css">
<link rel="stylesheet" href="assets/css/color.css">
<link rel="stylesheet" href="assets/css/responsive.css">
<link rel="stylesheet" href="assets/css/checkout.css">
{{--<link rel="stylesheet" href="assets/css/header.css">--}}
<link rel="stylesheet" href="assets/css/user.css">
